version: 0.0
os: linux
files:
  - source: /
    destination: /srv/sonic_sketches
permissions:
  - object: /srv
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: script/codedeploy-post-install
      timeout: 1200
      runas: ubuntu
