version: 0.0
os: linux
files:
  - source: /
    destination: /srv/sonic_sketches
permissions:
  - object: /srv/sonic_sketches
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: script/deps
      timeout: 600
      runas: ubuntu
